apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demoapp
  name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoapp
    spec:
      containers:
      - image: demoapp:demo
        name: demoapp
        resources: {}
        volumeMounts:
          - name: demosource
            mountPath: /demoapp
      volumes:
        - name: demosource
          hostPath:
            path: /Users/hyw208/Documents/Code/python/minikube_demo/demoapp
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demoapp
  name: demoapp
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: "4444"
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: demoapp
  type: NodePort
status:
  loadBalancer: {}
